#!/bin/bash
set -e

. /usr/local/share/atlassian/common.sh

if [ "$CONTEXT_PATH" == "ROOT" -o -z "$CONTEXT_PATH" ]; then
  CONTEXT_PATH=
else
  CONTEXT_PATH="/$CONTEXT_PATH"
fi

#xmlstarlet ed -u '//Context/@path' -v "$CONTEXT_PATH" conf/server-backup.xml > conf/server.xml

if [ -n "$DATABASE_URL" ]; then
  extract_database_url "$DATABASE_URL" DB /opt/bitbucket/lib
  if [ ! -f $BITBUCKET_HOME/bitbucket.properties ]; then
  cat << EOF > $BITBUCKET_HOME/bitbucket.properties
#>*******************************************************
#> Migrated to database at $DB_JDBC_URL
#> Generated by launch script on `date`
#>*******************************************************
jdbc.driver=$DB_JDBC_DRIVER
jdbc.url=$DB_JDBC_URL
jdbc.user=$DB_USER
jdbc.password=$DB_PASSWORD
EOF
  fi
fi

#if [ -n "$USE_SSL_PROXY" ]; then
#  echo "Use SSL Proxy"
#  cp ${BITBUCKET_INST}/conf/server.xml ${BITBUCKET_INST}/conf/server-backup.xml
#  xmlstarlet ed --insert "/Server/Service/Connector" --type attr -n scheme -v "https" ${BITBUCKET_INST}/conf/server-backup.xml |
#    xmlstarlet ed --insert "/Server/Service/Connector" --type attr -n proxyName -v "$USE_SSL_PROXY" |
#    xmlstarlet ed --insert "/Server/Service/Connector" --type attr -n proxyPort -v "443"  |
#    xmlstarlet ed --insert "/Server/Service/Connector" --type attr -n secure -v "true" > ${BITBUCKET_INST}/conf/server.xml
#fi